version: '3'
services:
  grafana:
    build: .
    container_name: grafana-server
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - "lib:/var/lib/grafana"
      - "log:/var/log/grafana"
      - "share:/usr/share/grafana"
      - "config:/etc/grafana"
    networks:
      - elk

volumes:
  lib: {}
  log: {}
  share: {}
  config: {}

networks:
  elk:
